### ISSUE TITLE
Fix loopback version freezing instructions

### ISSUE THREAD

**Issue by pulkitsinghal** [pulkitsinghal/loopback-zero-to-hero#1]
Change `#` to be `@` in the following commands:

```
$ npm install --save --save-exact loopback#2.18.0
$ npm install --save --save-exact loopback-boot#2.8.1
$ npm install --save --save-exact loopback-datasource-juggler#2.31.0
```

**Comment by kamal0808** [comment]
![screenshot 2016-03-12 02 47 39](https://cloud.githubusercontent.com/assets/15616412/13715664/5408a280-e7fc-11e5-9f7e-531f48307dbf.png)

versions in install commands in installed versions do not match

**Comment by pulkitsinghal** [comment]
fix typo `peeking`

![screen shot 2016-03-11 at 3 24 08 pm](https://cloud.githubusercontent.com/assets/821963/13715923/639ee650-e79d-11e5-985e-8462f7a58e92.png)
